function frequency_filter = log_gabor_frequency( ...
    f_x, ...
    f_y, ...
    center_frequency, ...
    bandwidth, ...
    direction)

Cb = 4 / (bandwidth^2 * log(2));
r = sqrt(f_x.^2 + f_y.^2);
R = exp( - Cb .* log( r ./ center_frequency ).^2 );
R(isnan(R)) = 0;

director = direction_to_director(direction);
uv = cat(3, f_x, f_y);
uv = uv ./ repmat(r, [1 1 2]);
uv(isnan(uv)) = 0;
Dk = sum( ...
    uv .* cat(3, ...
        ones(size(f_x)) .* director(1), ...
        ones(size(f_x)) .* director(2)), ...
    3);
Dk(Dk < 0) = 0;
Dk = Dk .^2;
frequency_filter = R .* Dk;
